name: 'Fleek Deploy Action'
description: 'Deploy Fleek Sites in Github actions'
author: 'Fleek Labs'
branding:
  icon: circle
  color: gray-dark
inputs:
  apiKey:
    description: 'Fleek Scoped Api Key'
    required: true
  workDir:
    description: 'Path to directory where fleek site is initialized (optional)'
    required: false
  commitHash:
    description: 'Commit Hash of configured git repository to deploy'
    required: false
outputs:
  deployUrl:
    description: 'Website Url to view the API'
runs:
  using: 'docker'
  image: 'Dockerfile'
